config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get 'discover', to: 'pages#discover'
  get 'welcome', to: 'welcome#login', :as => :login
  post 'newsletter/subscribe', to: 'users#subscribe', as: :subscribe_to_newsletter

  scope '(:locale)', locale: /en|fr/ do
    devise_for :users, :controllers => { :invitations => 'users/invitations' }
    root to: 'pages#home'

    # resources :perfumes, only: [:show, :index]
    # resources :kits, only: [:index, :show]
    resources :order_items, only: [:create, :destroy]
    resources :orders, only: [:new, :create, :update]
    namespace :checkout do
      resource :address, only: [:edit, :create]
      resource :payment, only: [:new, :create]
      resource :confirmation, only: [:show]
    end

    namespace :account do
      resource :dashboard, only: [:show]
      resource :profile, only: [:edit, :update]
      resources :orders, only: [:index]
      resources :kits, only: [:show]
      resources :perfumes, only: [:show] do
        post "reviews/:review_id/update_review" => "reviews#update_review"
        resources :reviews, only: [:create, :update]

      end
        # post 'perfumes/step1', to: 'perfumes#step1', as: 'step1'
        # post 'perfumes/step2', to: 'perfumes#step1', as: 'step2'
        # post 'perfumes/step3', to: 'perfumes#step1', as: 'step3'
        # post 'perfumes/step4', to: 'perfumes#step1', as: 'step4'
        # post 'perfumes/step5', to: 'perfumes#step1', as: 'step5'
        # post 'perfumes/step6', to: 'perfumes#step1', as: 'step6'
    end
  # resources :coupons, except: [:index]
  # resources :kits, except: [:show]
  end
end

app/views/shared/_address_card.html.erb
<div class="address-card">
  <div class="address-card-description">
    <h2><%=address.first_name%> <%=address.last_name%> </h2>
    <ul class="list-unstyled">
      <li><%=address.street%></li>
      <li><%=address.zip_code%></li>
      <li><%=address.city%></li>
      <li><%=address.country_code%></li>
    </ul>
  </div>
  <%= link_to "Envoyer à cette addresse", order_path(id:session[:order_id], address_id:address.id), method: "put", class: "address-card-description-link" %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert" id="notice">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice.html_safe %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert" id="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="wrapper-footer1">
  <div class="container">
    <div class="row">
      <div class="company col-xs-12 col-sm-2">
            <div class="text-left">
              <ul>
                <li id="footer-nl" class="list-footer"><strong><%= t('.about') %></strong></li>
                <li id="footer-nl" class="list-footer">
                <%= link_to t('.creator'), discover_path, html_options = {class: "footer-links"} %></li>
                <li id="footer-nl" class="list-footer">
                <%= link_to t('.discover'), discover_path, html_options = {class: "footer-links"} %></li>
                <li id="footer-nl" class="list-footer"><%= link_to t('.blog'), discover_path, html_options = {class: "footer-links"} %></li>
              </ul>
            </div>
      </div>
      <div class="company col-xs-12 col-sm-2">

            <div class="text-left">
              <ul>
                <li id="footer-nl" class="list-footer"><strong><%= t('.more') %></strong></li>
                <li id="footer-nl" class="list-footer"><%= link_to t('.terms'), discover_path, html_options = {class: "footer-links"} %></li>
                <li id="footer-nl" class="list-footer"><%= link_to t('.privacy'), discover_path, html_options = {class: "footer-links"} %></li>
              </ul>
            </div>
    </div>
      <div class="text-center col-xs-6 col-sm-4">
        <div class="social">
          <ul class="list-inline">
            <li><a href=""><i class="fa fa-youtube fa-2x icons"></i></a></li>
            <li><a href=""><i class="fa fa-instagram fa-2x icons"></i></a></li>
            <li><a href=""><i class="fa fa-facebook fa-2x icons"></i></a></li>
            <li><a href=""><i class="fa fa-twitter fa-2x icons"></i></a></li>
          </ul>
        </div>
        <div class="dropdown">
          <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"><%= params[:locale] == "fr" ? "Français" : "English" %>
          <span class="caret"></span>
          </button>
         <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu3">
           <li><%=link_to(t('.language-fr'), params.merge(locale: 'fr'))%></li>
           <li><%=link_to(t('.language-en'), params.merge(locale: 'en'))%></li>
          </ul>
        </div>
      </div>
      <div class="col-xs-8 col-sm-4 text-left">
        <p id="footer-nl"><%= t('.nl_subtitle') %></p>
        <p>
          <%= form_tag subscribe_to_newsletter_path, class: "footer-form" do %>
            <div class="form-group">
              <input type="text" name="email" class="hpsearch" placeholder=<%= t('.nl_email') %>>
            </div>
          <button type="submit" class="btn btn-success" ><%= t('.nl_button') %></button>
          <% end %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class='navbar-juliette'>
  <div class="navbar-side">
    <div class="navbar-wagon-item">
        <div class="dropdown">
        <i class="fa fa-bars menu-logo dropdown-toggle" data-toggle="dropdown"></i>
          <ul class="dropdown-menu dropdown-menu-left navbar-dropdown-menu-left">
            <li><a href=""><%= t('.artist') %></a></li>
            <li><a href=""><%= t('.collection') %></a></li>
            <li><a href=""><%= t('.blog') %></a></li>
            <li><a href=""><%= t('.top_call_to_action') %></a></li>
          </ul>
        </div>
      </div>
    <div class="navbar-side-left hidden-xs hidden-sm">
      <a href=""><%= t('.artist') %></a>
      <a href=""><%= t('.collection') %></a>
    </div>
  </div>
  <%= link_to root_path, class: "navbar-logo hidden-xs", id: "logo-font" do %>
    Juliette Lacroix
  <% end %>
  <%= link_to root_path, class: "navbar-logo hidden-sm hidden-md hidden-lg", id: "logo-font" do %>
    JL
  <% end %>
  <div class='navbar-side'>
    <div class="navbar-side-right hidden-xs hidden-sm">
      <a href=""><%= t('.blog') %></a>
      <%= link_to t(".top_call_to_action"), discover_path%>
    </div>

    <% if user_signed_in? %>


      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item" id="logo-perfume">
        <div class="dropdown">
          <%= image_tag "logo.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to account_dashboard_path do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
              <% end %>
            </li>
            <li>
              <%= link_to new_order_path do %>
                <i class="fa fa-shopping-basket"></i>  <%= t ".basket", default: "Panier" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
    <% else %>

      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#login-modal" id="hp_login_modal">Se connecter</button>

      <%= render 'welcome/login_modal' %>



    <% end %>

  </div>


</div>
</div>

app/views/shared/_perfume_pic.html.erb
<div class="perfume-pic">
  <a class="card-link" href="#" ></a>
  <%=image_tag('perfume.jpg')%>
</div>