config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get 'discover', to: 'pages#discover'
  get 'welcome', to: 'welcome#login', :as => :login
  post 'newsletter/subscribe', to: 'users#subscribe', as: :subscribe_to_newsletter

  scope '(:locale)', locale: /en|fr/ do
    devise_for :users, :controllers => { :invitations => 'users/invitations' }
    root to: 'pages#home'

    # resources :perfumes, only: [:show, :index]
    # resources :kits, only: [:index, :show]
    resources :order_items, only: [:create, :destroy]
    resources :orders, only: [:new, :create, :update]
    namespace :checkout do
      resource :address, only: [:edit, :create]
      resource :payment, only: [:new, :create]
      resource :confirmation, only: [:show]
    end

    namespace :account do
      resource :dashboard, only: [:show]
      resource :profile, only: [:edit, :update]
      resources :orders, only: [:index]
      resources :kits, only: [:show]
      resources :perfumes, only: [:show] do
        post "reviews/:review_id/update_review" => "reviews#update_review"
        resources :reviews, only: [:create, :update]

      end
        # post 'perfumes/step1', to: 'perfumes#step1', as: 'step1'
        # post 'perfumes/step2', to: 'perfumes#step1', as: 'step2'
        # post 'perfumes/step3', to: 'perfumes#step1', as: 'step3'
        # post 'perfumes/step4', to: 'perfumes#step1', as: 'step4'
        # post 'perfumes/step5', to: 'perfumes#step1', as: 'step5'
        # post 'perfumes/step6', to: 'perfumes#step1', as: 'step6'
    end
  # resources :coupons, except: [:index]
  # resources :kits, except: [:show]
  end
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  address_id :integer
#

class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :address
  has_many :order_items
  validates :user_id, presence: :true
  validates :address_id, presence: :true
  monetize :amount_cents

end

app/controllers/orders_controller.rb
# == Schema Information
#
# Table name: orders
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  address_id :integer
#

class OrdersController < ApplicationController

  def new
    # Tentative pour retrouver le panier précédent non fini en cas de log out sans paiement
    # if current_user.orders.where(state:"pending")

    # end
    if session[:order_id]
      @order = current_user.orders.where(state: "pending").find(session[:order_id])
    else
      @order = current_user.orders.create!(address: current_user.addresses.last, state: "pending")
      session[:order_id] = @order.id
    end

    @order.amount = 0
    @order.order_items.each do |order_item|
      @order.amount += order_item.amount
    end

    @order.save
  end

  def update
    @order = current_user.orders.where(state: "pending").find(session[:order_id])

    if @order.update!(address_id:params[:address_id])
      redirect_to new_order_path
    else
      flash[:alert] = "Erreur dans votre adresse. Veuillez en choisir une autre"
      redirect_to edit_checkout_address_path
    end
  end

  def create
    @order = current_user.orders.where(state:'pending').find(params[:order_id])
    if @order.amount == 0
      flash[:alert] = "Your cart is empty"
      redirect_to new_order_path
    else
    redirect_to new_checkout_payment_path
    end
  end
end

app/helpers/orders_helper.rb
# == Schema Information
#
# Table name: orders
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  address_id :integer
#

module OrdersHelper
end

app/views/orders/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h3><%= t('.title')%></h3>
      <p>Voici le récapitulatif des articles ajoutés à votre panier. </p>
    </div>
  </div>
  <div class="frame">
    <div class="row">
      <div class="col-xs-9 col-sm-7 col-sm-offset-1">
        <h4>Article(s) sélectionné(s)</h4>
      </div>
      <div class="col-xs-1"><h4 class="text-center">Quantité</h4></div>
      <div class="col-xs-1"><h4 class="text-center">Prix</h4></div>
    </div>
    <% @order.order_items.each do |order_item| %>
      <div class="row">
        <div class="col-xs-9 col-sm-7 col-sm-offset-1">
          <% if order_item.product_type == "Perfume"%>
            <h4> <%= link_to account_perfume_path(id:order_item.product_id) do %>
              <%= order_item.product.name %> - Ref : <%= order_item.product_sku %>
            <%end%> </h4>
          <%else%>
            <h4><%= order_item.product.name %> - Ref : <%= order_item.product_sku %></h4>
          <%end%>
        </div>
        <div class="col-xs-1 text-center">
          <h4><%= order_item.quantity %></h4>
        </div>
        <div class="col-xs-1 text-center">
          <h4><%= humanized_money_with_symbol(order_item.amount) %></h4>
        </div>
        <div class="col-xs-1 text-center">
        <h4><%= link_to order_item_path(id:order_item.id), method: "delete" do%>
          <i class="fa fa-trash-o"></i>
        <%end%></h4>
        </div>
      </div>
    <%end%>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-1" id="delivery">
      <h4>Vos bénéfices</h4>
      <div class="flexbox"><i class="fa fa-truck small-right-margin"></i><span>Livraison gratuite en France métropolitaine</span></div>
      <div class="flexbox"><i class="fa fa-reply small-right-margin"> </i>Retours gratuits
      </div>
      <div class="flexbox"><i class="fa fa-smile-o small-right-margin"> </i>Satisfait(e) ou remboursé(e)
      </div>
    </div>
    <div class='col-xs-12 col-sm-6'>
      <div class="totalcolor">
        <div>
          <h4>Total à payer</h4>
        </div>
        <div><h4 class="text-left"><%= humanized_money_with_symbol(@order.amount) %></h4></div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class = "col-xs-12 col-sm-offset-1 col-sm-8">
      <h4>Confirmer votre adresse de livraison</h4>

      <div class="frame_address">
        <ul class="list-unstyled">
          <li><%= @order.address.first_name %> <%= @order.address.last_name %></li>
          <li><%= @order.address.street %></li>
          <li><%= @order.address.city %></li>
          <li><%= @order.address.zip_code %></li>
          <li><%= link_to("Modifier", edit_checkout_address_path)%><i class="fa fa-pencil"></i></li>
        </ul>
      </div>
    </div>
  </div>
  <% if @order.amount_cents == 0 %>
    <h3 class="text-center">Votre panier est vide</h3 class="text-center">
  <%else%>
    <div class="text-center">
      <%= form_tag checkout_payment_path do %>
        <%= hidden_field_tag 'order_id', @order.id %>
         <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
      data-email="<%=current_user.email%>"
      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
      data-name="My Order - Juliette Lacroix"
      data-description="<%= @order.order_items.count %> article - <%= humanized_money_with_symbol(@order.amount) %>"
      data-amount="<%= @order.amount_cents %>"
      data-currency="EUR"
      data-locale = "auto"
      data-label = "Payer">
      </script>
      <% end %>
    </div>
  <%end%>
  <h4 class="text-center"><%= link_to "Retourner à mon espace", account_dashboard_path %></h4>
</div>

<div class="min-height"></div>