config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get 'discover', to: 'pages#discover'
  get 'welcome', to: 'welcome#login', :as => :login
  post 'newsletter/subscribe', to: 'users#subscribe', as: :subscribe_to_newsletter

  scope '(:locale)', locale: /en|fr/ do
    devise_for :users, :controllers => { :invitations => 'users/invitations' }
    root to: 'pages#home'

    # resources :perfumes, only: [:show, :index]
    # resources :kits, only: [:index, :show]
    resources :order_items, only: [:create, :destroy]
    resources :orders, only: [:new, :create, :update]
    namespace :checkout do
      resource :address, only: [:edit, :create]
      resource :payment, only: [:new, :create]
      resource :confirmation, only: [:show]
    end

    namespace :account do
      resource :dashboard, only: [:show]
      resource :profile, only: [:edit, :update]
      resources :orders, only: [:index]
      resources :kits, only: [:show]
      resources :perfumes, only: [:show] do
        post "reviews/:review_id/update_review" => "reviews#update_review"
        resources :reviews, only: [:create, :update]

      end
        # post 'perfumes/step1', to: 'perfumes#step1', as: 'step1'
        # post 'perfumes/step2', to: 'perfumes#step1', as: 'step2'
        # post 'perfumes/step3', to: 'perfumes#step1', as: 'step3'
        # post 'perfumes/step4', to: 'perfumes#step1', as: 'step4'
        # post 'perfumes/step5', to: 'perfumes#step1', as: 'step5'
        # post 'perfumes/step6', to: 'perfumes#step1', as: 'step6'
    end
  # resources :coupons, except: [:index]
  # resources :kits, except: [:show]
  end
end

app/views/pages/_banner.html.erb
<!-- <div class="banner" id="banner" style="background: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://static.pexels.com/photos/6404/woman-girl-young-beauty.jpg');"> -->
  <div class="banner-content">
    <h1><%= t('.tagline') %></h1>
    <p><%= t('.sub_tagline') %></p>
    <div class="cta">
      <p>
        <!-- <form class="form-inline">
              <div class="form-group">
                <input type="text" class="hpsearch" placeholder="<%= t('.invitation_text') %>" name="where">
              </div>
          <button type="submit" class="btn btn-success"><%= t('.invitation_button') %></button>
          </form> -->
      </p>
    </div>
      <p>
        <a href="#experience"><%= t('.cta_text') %></a>
        <a href="#">
          <i class="fa fa-angle-down pulse arrow"></i>
        </a>
      </p>
  </div>
</div>

app/views/pages/discover.html.erb
<div class="wrapper-grey">
  <div class="container padded">
    <div class="row">
        <div class="hptitle padded"><h3 class="text-center section-title img-reveal col-xs-12">Vivez une expérience olfactive unique</h3></div>
      <div class="col-xs-12 col-sm-6">
        <div class="pic-frame padded">
        <img class="pic-home text-center " src="https://static.pexels.com/photos/6675/flight-mountains-sky-flying.jpeg">
        </div>
      </div>
      <div class="col-xs-12 col-sm-6">
        <div class="section-list padded">
          <p>5 testeurs pour découvrir tous les parfums de la gamme aux multiples personnalités.</p>
          <p>Une découverte personnalisée pour apprendre sur chaque parfum et trouvez celui qui vous correspond.</p>
          <p>Votre parfum exclusif disponible en un clic, livré chez vous dans son coffret et avec sa recharge mobile.</p>
        <p class="section-par text-center"><%= link_to t(".top_call_to_action", default: "Recevoir une invitation"), "/", class: "navbar-wagon-item navbar-wagon-button btn" %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<!-- ############## Pour mettre de la vidéo> -->
<div>
<div class="container-video">
<%= video_tag("juliettelacroix1.mp4", poster: "juliettelacroix1.png", autobuffer: true, autoplay: true, :loop => true, :html_options => {class: "bgvid"})%>


    <div class="overlay">
      <h1><%= t('.title') %></h1>
      <h3><%= t('.subtitle') %></h3>
      <div class="banner-invitation padded">
      </div>


        <%if user_signed_in? %>
          <h4><%=t(".h2banner")%></h4>
          <div class="small-padded"></div>
          <%= link_to account_dashboard_path do %>
            <div class="btn btn-default", style="opacity:0.5;"><%= t('.dashboard') %></div>
          <% end %>
        <%elsif @invitation%>
          <h5><%=t(".nbinvitations")%> <%=@invitation_nb%> </h5>
          <div class="small-padded"></div>
          <%= simple_form_for @invited, as: "user", url: invitation_path("user"), method: :post, html: { class: 'form-inline home-form' } do |f| %>
          <% User.invite_key_fields.each do |field| -%>
            <%= f.input field, input_html: {class: "hpsearch"}, placeholder: I18n.t('.simple_form.placeholders.email'), label: false %>
          <% end -%>

          <%= f.button :submit, t("devise.invitations.new.submit_button") %>
        <% end %>
        <%else%>
          <h4><%= t(".no_more_invitation")%></h4>
          <form class="form-inline home-form">
            <div class="form-group">
              <input type="text" name="email" class="hpsearch", placeholder= "<%= t('.subscribe_newsletter') %>">
            </div>
          <button type="submit" class="btn btn-success"><%= t('.nl_button') %></button>
          </form>
        <%end%>
      <div class="overlay-bis banner-experience">
        <a href="#experience" id="down">
          <i class="fa fa-angle-down arrow"></i>
        </a>
      </div>
    </div>
  </div>
</div>
</div>

<div class="wrapper-grey" id="experience">
  <div class="container padded">
    <div class="row">
        <div class="hptitle"><h3 class="text-center section-title col-xs-12"><%= t('.title1') %></h3></div>
      <div class="col-xs-12 col-sm-6">
        <div class="pic-frame">
        <%= image_tag 'scentbird.jpg', class: "pic-home text-center"%>

        </div>
      </div>
      <div id="experience" class="col-xs-12 col-sm-6">
        <p class="section-par"><%= t('.par1') %></p>
        <p class="section-par"><%= t('.par1-2') %></p>
        <p class="text-center padded"><%= link_to t(".cta-par1"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %></p>
      </div>
    </div>
  </div>
</div>


<div class="wrapper-gold">
  <div class="container padded">
        <div class="hptitle"><h3 class="text-center section-title col-xs-12"><%= t('.title2') %></h3></div>
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <p class="section-par"><%= t('.par2') %></p>
        <p class="section-par"><%= t('.par2-2') %></p>
        <p class="section-par"><%= t('.par2-3') %></p>
      </div>
      <div class="col-xs-12 col-sm-6">
        <div class="pic-frame">
        <img class="pic-home text-center" src="https://static.pexels.com/photos/6404/woman-girl-young-beauty.jpg">
        </div>
      </div>
    </div>
  </div>
</div>

<div class="wrapper-grey">
  <div class="container padded">
    <div class="row">
        <div class="hptitle"><h3 class="text-center section-title col-xs-12"><%= t('.title3') %></h3></div>
      <div class="col-xs-12 col-sm-6">
        <div class="pic-frame">
        <%= image_tag 'perfumer.jpg', class: "pic-home text-center"%>
        </div>
      </div>
      <div id="experience" class="col-xs-12 col-sm-6">
        <p class="section-par"><%= t('.par3') %></p>
        <p class="section-par"><%= t('.par3-2') %></p>
        <p class="text-center padded"><%= link_to t(".cta-par3"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %></p>
      </div>
    </div>
  </div>
</div>

<div class="wrapper-gold">
  <div class="container">
    <div class="text-center">
      <div class="hptitle">
      <h3><%= t('.testimony') %></h3>
      </div>
    </div>
    <!-- <div id="owl-hp" class="owl-carousel owl-theme col-xs-12 col-sm-6">
      <div class="item"><h1>1</h1></div>
      <div class="item"><h1>2</h1></div>
      <div class="item"><h1>3</h1></div>
    </div> -->
    <div class="text-center">
      <%=image_tag('femme_sourire.jpg', :class => "avatar-large")%>
      <h4><%= t('.testimony-name') %></h4>
      <p>"<%= t('.testimony-desc') %>"</p>
    </div>
  </div>
</div>

<%= content_for(:after_js) do %>
 <%= javascript_tag do %>
    window.sr = ScrollReveal();
    sr.reveal('.img-reveal', { reset: true});
    //window.scrollReveal = new scrollReveal();
  <% end %>
<% end %>